title: Anja Alsen
logo: "/images/image(1).png"
description: > 
  Operations Team Lead at ASB Hamburg | Budding Data Analyst  
  <br><br>
  <a href="https://www.linkedin.com/in/anja-a-141ba5150/">View My LinkedIn Profile</a>  
<a href=" https://public.tableau.com/app/profile/anja.alsen/vizzes">View My Tableau Public Profile</a>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: UA-000000-0

