description: > 
  Operations Team Lead at ASB Hamburg | Budding Data Analyst  
  <br><br>
  <a href="https://www.linkedin.com/in/anja-a-141ba5150/">LinkedIn Profile</a>  
  <br>
  <a href="https://www.github.com/anjaalsen">GitHub Profile</a>  
  <br>
  <a href="https://www.public.tableau.com/app/profile/anja.alsen/vizzes">Tableau Public Profile</a>



